apiVersion: v1
kind: List
metadata:
  name: iks-ibmcloud-operator-yaml
items:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: operatorhubio-catalog
      namespace: ibm-system
      labels:
        razee/watch-resource: "detail"
    spec:
      sourceType: grpc
      image: quay.io/operator-framework/upstream-community-operators:latest
      displayName: Community Operators
      publisher: OperatorHub.io
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ibmcloud-operator
      namespace: ibm-operators
      labels:
        razee/watch-resource: "detail"
    spec:
      channel: alpha
      installPlanApproval: Automatic
      name: ibmcloud-operator
      source: operatorhubio-catalog
      sourceNamespace: ibm-system
      startingCSV: ibmcloud-operator.v0.1.11
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: ibmcloud-operator-admin
      labels:
        razee/watch-resource: "lite"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
      - kind: ServiceAccount
        name: default
        namespace: ibm-operators
  - apiVersion: v1
    data:
      api-key: <base64_encoded_apikey>
      region: dXMtc291dGg=
    kind: Secret
    metadata:
      labels:
        app.kubernetes.io/name: ibmcloud-operator
        seed.ibm.com/ibmcloud-token: apikey
        razee/watch-resource: "detail"
      name: secret-ibm-cloud-operator
      namespace: ibm-operators
    type: Opaque
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: config-ibm-cloud-operator
      namespace: ibm-operators
      labels:
        app.kubernetes.io/name: ibmcloud-operator
    data:
      org: ""
      region: "us-south"
      resourcegroup: "default"
      resourcegroupid: "64de66b9d89d49bb87a27b0536324ba8"
      space: ""
      user: ""
